name = "group-control-bot-builder"
main = "index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "tgbot"
database_id = "2ff37c13-aea2-4696-848f-65368fac648f"

[triggers]
crons = ["* * * * *"]
